version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: kabadiwala
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kabadiwaladb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://kabadiwala:password@db/kabadiwaladb

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
